### ISSUE TITLE
Any feedback after one year :)

### ISSUE THREAD

**Issue by besarthoxhaj** [julienvincent/modelizr#16]
Hi Julien,

I think the idea of **modelizr** is great! :)

Do you have any feedback after one year?

**Comment by julienvincent** [comment]
Hi @besarthoxhaj,

I think a lot of my initial reasons for writing this library have now been solved better by other people. Personally I no longer use this library for my projects and instead use apollo.

I would suggest looking at [apollo](https://github.com/apollographql/apollo-client) instead of modelizr. The team over there have done an amazing job in producing a collection of libraries that should handle any graphql use-case in JS (and very well).

Thank you for showing an interest, but I think Modelizr is dead. Long live Apollo :)

**Comment by besarthoxhaj** [comment]
@julienvincent thanks for your quick reply. Will have a look at Apollo :)
